project_id = "tewjsubccoizrjroaydy"

[functions.google-ads-forecast]
verify_jwt = false

[functions.meta-forecast]
verify_jwt = false

[functions.meta-rf-prediction]
verify_jwt = false

[functions.meta-accounts]
verify_jwt = true

[functions.sync-platform-accounts]
verify_jwt = true
