import { serve } from "https://deno.land/std@0.190.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
};

interface SendInsightsEmailRequest {
  recipientEmails: string[];
  campaignName: string;
  platforms: string[];
  analysisResult: string;
  senderName: string;
}

const handler = async (req: Request): Promise<Response> => {
  // Handle CORS preflight requests
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");
    if (!RESEND_API_KEY) {
      console.log("RESEND_API_KEY not configured, skipping email send");
      return new Response(
        JSON.stringify({ success: true, message: "Email sending not configured" }),
        { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const { recipientEmails, campaignName, platforms, analysisResult, senderName }: SendInsightsEmailRequest = await req.json();

    console.log("[SEND-INSIGHTS-EMAIL] Sending to:", recipientEmails);

    if (!recipientEmails || recipientEmails.length === 0) {
      return new Response(
        JSON.stringify({ error: "No recipients specified" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Format platforms for display
    const platformsDisplay = platforms.map(p => 
      p === 'meta' ? 'Meta (Facebook/Instagram)' : p.charAt(0).toUpperCase() + p.slice(1)
    ).join(', ');

    // Convert markdown-style formatting to HTML
    const formattedAnalysis = analysisResult
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/\n---\n/g, '<hr />')
      .replace(/\n/g, '<br />')
      .replace(/^### (.+)$/gm, '<h3>$1</h3>')
      .replace(/^## (.+)$/gm, '<h2>$1</h2>')
      .replace(/^# (.+)$/gm, '<h1>$1</h1>');

    const emailHtml = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 20px; background-color: #f4f4f5; }
    .container { max-width: 600px; margin: 0 auto; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
    .header { background: linear-gradient(135deg, #6366f1, #8b5cf6); color: white; padding: 30px; text-align: center; }
    .content { padding: 30px; }
    .meta-info { background: #f9fafb; padding: 15px; border-radius: 6px; margin-bottom: 20px; border: 1px solid #e5e7eb; }
    .analysis { background: #f9fafb; padding: 20px; border-radius: 6px; border: 1px solid #e5e7eb; }
    h1, h2, h3 { color: #1f2937; }
    hr { border: none; border-top: 1px solid #e5e7eb; margin: 20px 0; }
    .footer { text-align: center; padding: 20px; color: #6b7280; font-size: 12px; background: #f4f4f5; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1 style="margin: 0; color: white;">📊 Campaign Insights Report</h1>
      <p style="margin: 10px 0 0 0; opacity: 0.9;">AI-Powered Performance Analysis</p>
    </div>
    <div class="content">
      <div class="meta-info">
        <p style="margin: 5px 0;"><strong>Campaign:</strong> ${campaignName}</p>
        <p style="margin: 5px 0;"><strong>Platforms:</strong> ${platformsDisplay}</p>
        <p style="margin: 5px 0;"><strong>Shared by:</strong> ${senderName}</p>
      </div>
      <div class="analysis">
        ${formattedAnalysis}
      </div>
    </div>
    <div class="footer">
      <p style="margin: 0;">This report was generated by ActiPlan Insights & Recommendations</p>
    </div>
  </div>
</body>
</html>
    `;

    // Send email using Resend API
    const emailResponse = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${RESEND_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: "ActiPlan <onboarding@resend.dev>",
        to: recipientEmails,
        subject: `Campaign Insights: ${campaignName}`,
        html: emailHtml,
      }),
    });

    if (!emailResponse.ok) {
      const errorText = await emailResponse.text();
      console.error("[SEND-INSIGHTS-EMAIL] Failed:", errorText);
      throw new Error(`Failed to send email: ${errorText}`);
    }

    const responseData = await emailResponse.json();
    console.log("[SEND-INSIGHTS-EMAIL] Sent successfully:", responseData);

    return new Response(
      JSON.stringify({ success: true, data: responseData }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error: any) {
    console.error("[SEND-INSIGHTS-EMAIL] Error:", error);
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
};

serve(handler);